### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by aacunningham** [enervee/sentry-django-settings#12]
Within the next couple weeks, sentry-django-settings will receive it's final update, mark itself as deprecated, and be archived. As Sentry's own library (https://github.com/getsentry/sentry-python) has added features, we have had less need for this library. We see no reason to continue this project and recommend directly using Sentry's SDK.

### Steps to migrate to sentry-sdk

The steps to migrate a project from this package to `sentry-sdk` are relatively minimal:

1. Remove `sentry_django_settings.apps.Sentry` from your `INSTALLED_APPS` configuration
2. Remove `sentry-django-settings` from your python dependencies and add `sentry-sdk`
3. (Optional) If you used the `git_sha_path` configuration option, you can add this snippet below the `SENTRY` definition to remove it and directly read the file:

```python
SENTRY = {
    ...,
    "git_sha_path": "path/to/git_sha"
}

# New snippet
with open(SENTRY.pop("git_sha_path", "r") as git_sha:
    SENTRY["release"] = git_sha.read().strip()
```

4. At the top of your `settings.py` file, add `import sentry_sdk`, and at the bottom of the file add the following snippet:

```python
if SENTRY.pop("enabled", False):
    sentry_sdk.init(
        integrations=[sentry_sdk.integrations.django.DjangoIntegration()],
        **SENTRY,
    )
```

If you use multiple settings.py files (for instance, a `settings-dev.py` and a `settings-prod.py`), you'll want to make sure these snippets are added after all modifications to the `SENTRY` dictionary are made (usually at the end of all final settings files). Any changes to the dictionary after calling `sentry_sdk.init` will have no effect, and calling the `init` method multiple times isn't documented so we can't recommend it.

**Comment by aacunningham** [comment]
@kris-anderson I think we're good to archive the repo when you have the time.

**Comment by kris-anderson** [comment]
Thank you @aacunningham
